<a href="https://colab.research.google.com/github/Bornitaadhikari/Simple-Line-Graph-and-Bar-chart/blob/main/Numpy_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import numpy as np

In [44]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [45]:
b=np.array([[9,0,0,8,7,9],[6,0,5,6,7,8]])
print(b)

[[9 0 0 8 7 9]
 [6 0 5 6 7 8]]


In [46]:
#get dimention
a.ndim

1

In [47]:
b.shape

(2, 6)

In [48]:
a.dtype

dtype('int64')

In [49]:
a.itemsize  #get size
b.itemsize

8

In [50]:
#get total size
a.size

3

In [51]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [52]:
#Get specific element [r,c]
a[1,5]

13

In [53]:
#Get specific row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [54]:
a[:,2]

array([ 3, 10])

In [55]:
#getting a little more fancy[startindex:endindix:stepsize]
a[1,1:-1:2]

array([ 9, 11, 13])

In [56]:
a[1,5]=20
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [57]:
b=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [58]:
#Get specific element(work outside in)
b[0,1,1]

4

In [59]:
b[:,1,:]

array([[3, 4]])

In [60]:
#all 0s marix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [62]:
#any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [63]:
#any other number(full like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [64]:
np.random.rand(4,2,3)


array([[[0.70912519, 0.26533013, 0.11847633],
        [0.98817483, 0.36073651, 0.3431459 ]],

       [[0.62694199, 0.23828779, 0.11995943],
        [0.55974566, 0.17773709, 0.82440044]],

       [[0.62651415, 0.21395255, 0.78676767],
        [0.91417038, 0.35057674, 0.68865498]],

       [[0.76000376, 0.62423493, 0.90495299],
        [0.27880954, 0.43893376, 0.62011689]]])

In [65]:
#random integer values
np.random.randint(-4,7,size=(3,4))

array([[ 5,  3,  1, -3],
       [ 6, -4,  1, -4],
       [ 3, -2,  4,  5]])

In [66]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [67]:
arr=np.array([[1,2,3],[4,4,6]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 4 6]
 [4 4 6]
 [4 4 6]]


In [68]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]=9
print(z)
output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [69]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)

[1 2 3]


In [70]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [71]:
a

array([1, 2, 3, 4])

In [72]:
a*2

array([2, 4, 6, 8])

In [73]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [74]:
a**2

array([ 1,  4,  9, 16])

In [75]:
#take the sin 
np.sin(a)


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

Linear Algebra

In [76]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [77]:
#find the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

Statistics

In [78]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
np.min(stats,axis=0)

array([1, 2, 3])

In [80]:
np.max(stats,axis=0)

array([4, 5, 6])

In [81]:
np.sum(stats,axis=0)

array([5, 7, 9])

Reorganizing array

In [82]:
before=np.array([[1,2,3,4],[7,8,9,10]])
print(before)
after=before.reshape((4,2))
print(after)

[[ 1  2  3  4]
 [ 7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 7  8]
 [ 9 10]]


In [83]:
#vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([4,5,6,7])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [1, 2, 3, 4],
       [4, 5, 6, 7]])

In [84]:
#Horizontal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])